services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: finance-control
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./sql/db_script.sql:/docker-entrypoint-initdb.d/db_script.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ptest"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: finance-control
      DB_USER: user
      DB_PASSWORD: test
    depends_on:
      db:
        condition: service_healthy

  web:
    image: nginx:alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  db:
    driver: local
