spring:
  jpa:
    open-in-view: true
  datasource:
    url: jdbc:postgresql://postgres:5433/finance-control-prd
  flyway:
    url: ${spring.datasource.url}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true

server:
  servlet:
    context-path: /api/finance-control
  compression:
    enabled: true
  error:
    include-message: always
  spring:
    url: ${SPRING-URL:localhost:8081}