server:
  port: ${server.port:8080}
  servlet:
    context-path: ${server.servlet.context-path:/dev-finance-control}
  compression:
    enabled: true
  error:
    include-message: always
  spring:
    url: localhost:${server.port:8080}

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:pass}
    url: ${spring.datasource.url:jdbc:postgresql://localhost:5432/finance-control-dev}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: ${APPLICATION_NAME:finance-control}
  main:
    web-application-type: servlet
  web:
    locale: pt_BR
    locale-resolver: fixed
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml
    default-schema: public
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_absent
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

springdoc:
  override-with-generic-response: false
  api-docs:
    enabled: true
  swagger-ui:
    server:
      list: http://localhost:${server.port}${server.servlet.context-path}
    path: /swagger-ui
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    filter: true
    disable-swagger-default-url: true
    csrf:
      enabled: false
    doc-expansion: none
  default-produces-media-type: application/json