const ph = name => `<i class="ph ph-${name}" aria-hidden="true"></i>`

export const Icons = {
    home:            () => ph('house'),
    dashboard:       () => ph('squares-four'),
    transaction:     () => ph('credit-card'),
    transfer:        () => ph('arrows-left-right'),
    accounts:        () => ph('wallet'),
    categories:      () => ph('tag'),
    institutions:    () => ph('bank'),
    locations:       () => ph('map-pin'),
    profile:         () => ph('user'),
    menu:            () => ph('list'),
    logout:          () => ph('sign-out'),
    delete:          () => ph('trash'),
    add:             () => ph('plus'),
    check:           () => ph('check-circle'),
    error:           () => ph('x-circle'),
    warning:         () => ph('warning'),
    info:            () => ph('info'),
    pencil:          () => ph('pencil'),
    broom:           () => ph('broom'),
    chevronLeft:     () => ph('caret-left'),
    eyeOpen:         () => ph('eye'),
    eyeClosed:       () => ph('eye-slash'),
    sun:             () => ph('sun'),
    moon:            () => ph('moon'),
    phone:           () => ph('phone'),
    wallet:          () => ph('wallet'),
    upload:          () => ph('upload'),
    statementImport: () => ph('file-arrow-up'),
    goals:           () => ph('flag'),
    achievements:    () => ph('trophy'),
    notifications:   () => ph('bell'),
    finny:           () => ph('piggy-bank'),
}
